
services:
###> doctrine/doctrine-bundle ###
  database:
    ports:
      - "5433:5432"
###< doctrine/doctrine-bundle ###
  php:
    environment:
      APP_ENV: dev
      APP_DEBUG: 1
    volumes:
      - ./:/var/www/html:rw
      - app_var:/var/www/html/var:rw
      - ./docker/php/conf.d/zz-opcache-dev.ini:/usr/local/etc/php/conf.d/zz-opcache-dev.ini:ro
  web:
    volumes:
      - ./public:/var/www/html/public:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
