
services:
###> doctrine/doctrine-bundle ###
  database:
    ports:
      - "5433:5432"
###< doctrine/doctrine-bundle ###
  php:
    environment:
      APP_ENV: dev
      APP_DEBUG: 1
      MAILER_DSN: smtp://mailer:1025
    volumes:
      - ./:/var/www/html:rw
      - app_var:/var/www/html/var:rw
      - ./docker/php/conf.d/zz-opcache-dev.ini:/usr/local/etc/php/conf.d/zz-opcache-dev.ini:ro
  web:
    volumes:
      - ./public:/var/www/html/public:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

###> symfony/mailer ###
  mailer:
    image: axllent/mailpit
    ports:
      - "1025:1025"
      - "8025:8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
###< symfony/mailer ###
