<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260213144921 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE application_attachment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, stored_name VARCHAR(255) NOT NULL, original_name VARCHAR(255) NOT NULL, mime_type VARCHAR(100) DEFAULT NULL, size INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, message_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_EDCE857537A1329 ON application_attachment (message_id)');
        $this->addSql('CREATE TABLE application_message (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, author_type VARCHAR(20) NOT NULL, body TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, application_id INT NOT NULL, author_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_5D03354C3E030ACD ON application_message (application_id)');
        $this->addSql('CREATE INDEX IDX_5D03354CF675F31B ON application_message (author_id)');
        $this->addSql('ALTER TABLE application_attachment ADD CONSTRAINT FK_EDCE857537A1329 FOREIGN KEY (message_id) REFERENCES application_message (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE application_message ADD CONSTRAINT FK_5D03354C3E030ACD FOREIGN KEY (application_id) REFERENCES application (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE application_message ADD CONSTRAINT FK_5D03354CF675F31B FOREIGN KEY (author_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE application_attachment DROP CONSTRAINT FK_EDCE857537A1329');
        $this->addSql('ALTER TABLE application_message DROP CONSTRAINT FK_5D03354C3E030ACD');
        $this->addSql('ALTER TABLE application_message DROP CONSTRAINT FK_5D03354CF675F31B');
        $this->addSql('DROP TABLE application_attachment');
        $this->addSql('DROP TABLE application_message');
    }
}
