<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260212101238 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE moderation_review (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, decision VARCHAR(20) NOT NULL, reason TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, offer_id INT NOT NULL, reviewer_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8ED28C7C53C674EE ON moderation_review (offer_id)');
        $this->addSql('CREATE INDEX IDX_8ED28C7C70574616 ON moderation_review (reviewer_id)');
        $this->addSql('ALTER TABLE moderation_review ADD CONSTRAINT FK_8ED28C7C53C674EE FOREIGN KEY (offer_id) REFERENCES offer (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE moderation_review ADD CONSTRAINT FK_8ED28C7C70574616 FOREIGN KEY (reviewer_id) REFERENCES "user" (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE moderation_review DROP CONSTRAINT FK_8ED28C7C53C674EE');
        $this->addSql('ALTER TABLE moderation_review DROP CONSTRAINT FK_8ED28C7C70574616');
        $this->addSql('DROP TABLE moderation_review');
    }
}
