<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260220103000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add automated offer moderation fields and append-only moderation review log; disable manual points claim in-review state';
    }

    public function up(Schema $schema): void
    {
        $this->addSql("ALTER TABLE offer ADD moderation_status VARCHAR(20) DEFAULT 'DRAFT' NOT NULL");
        $this->addSql('ALTER TABLE offer ADD moderation_reason_code VARCHAR(80) DEFAULT NULL');
        $this->addSql('ALTER TABLE offer ADD moderation_reason TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE offer ADD moderation_score INT DEFAULT 0 NOT NULL');
        $this->addSql("ALTER TABLE offer ADD moderation_rule_version VARCHAR(40) DEFAULT 'offer_moderation_v1_2026_02' NOT NULL");
        $this->addSql('ALTER TABLE offer ADD moderated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql("UPDATE offer SET moderation_status = CASE WHEN status = 'PUBLISHED' THEN 'APPROVED' ELSE 'DRAFT' END");
        $this->addSql("UPDATE offer SET moderated_at = published_at WHERE status = 'PUBLISHED'");
        $this->addSql("UPDATE offer SET moderation_reason_code = 'LEGACY_APPROVED', moderation_reason = 'Approved before automated moderation rollout' WHERE status = 'PUBLISHED'");

        $this->addSql('CREATE TABLE moderation_review (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, offer_id INT NOT NULL, actor_id INT DEFAULT NULL, action VARCHAR(40) NOT NULL, reason_code VARCHAR(80) DEFAULT NULL, reason_text TEXT DEFAULT NULL, moderation_score INT DEFAULT 0 NOT NULL, rule_version VARCHAR(40) NOT NULL, metadata JSON DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_4F7A9B2D53C674EE ON moderation_review (offer_id)');
        $this->addSql('CREATE INDEX IDX_4F7A9B2D010A4ECE ON moderation_review (actor_id)');
        $this->addSql('CREATE INDEX idx_moderation_review_offer_created_at ON moderation_review (offer_id, created_at)');
        $this->addSql('ALTER TABLE moderation_review ADD CONSTRAINT FK_4F7A9B2D53C674EE FOREIGN KEY (offer_id) REFERENCES offer (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE moderation_review ADD CONSTRAINT FK_4F7A9B2D010A4ECE FOREIGN KEY (actor_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql("UPDATE points_claim SET status = 'REJECTED', decision_reason_code = COALESCE(decision_reason_code, 'INSUFFICIENT_EVIDENCE_SCORE'), decision_reason = COALESCE(decision_reason, 'Rejected during automatic moderation rollout'), reviewed_at = COALESCE(reviewed_at, CURRENT_TIMESTAMP) WHERE status = 'IN_REVIEW'");
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE moderation_review DROP CONSTRAINT FK_4F7A9B2D53C674EE');
        $this->addSql('ALTER TABLE moderation_review DROP CONSTRAINT FK_4F7A9B2D010A4ECE');
        $this->addSql('DROP TABLE moderation_review');

        $this->addSql('ALTER TABLE offer DROP moderation_status');
        $this->addSql('ALTER TABLE offer DROP moderation_reason_code');
        $this->addSql('ALTER TABLE offer DROP moderation_reason');
        $this->addSql('ALTER TABLE offer DROP moderation_score');
        $this->addSql('ALTER TABLE offer DROP moderation_rule_version');
        $this->addSql('ALTER TABLE offer DROP moderated_at');
    }
}
