<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260218170500 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add recruiter plan fields to company and append-only recruiter subscription payments';
    }

    public function up(Schema $schema): void
    {
        $this->addSql("ALTER TABLE company ADD recruiter_plan_code VARCHAR(20) DEFAULT 'STARTER' NOT NULL");
        $this->addSql('ALTER TABLE company ADD recruiter_plan_started_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE company ADD recruiter_plan_expires_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');

        $this->addSql('CREATE TABLE recruiter_subscription_payment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, company_id INT NOT NULL, initiated_by_id INT DEFAULT NULL, plan_code VARCHAR(20) NOT NULL, amount_cents INT NOT NULL, currency_code VARCHAR(3) NOT NULL, provider VARCHAR(40) NOT NULL, provider_session_id VARCHAR(120) DEFAULT NULL, provider_payment_id VARCHAR(120) DEFAULT NULL, status VARCHAR(20) NOT NULL, idempotency_key VARCHAR(120) NOT NULL, provider_payload JSON DEFAULT NULL, paid_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, period_start TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, period_end TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_333D85CD979B1AD6 ON recruiter_subscription_payment (company_id)');
        $this->addSql('CREATE INDEX IDX_333D85CDD09FDF9D ON recruiter_subscription_payment (initiated_by_id)');
        $this->addSql('CREATE INDEX idx_recruiter_payment_provider_session ON recruiter_subscription_payment (provider, provider_session_id)');
        $this->addSql('CREATE INDEX idx_recruiter_payment_provider_payment ON recruiter_subscription_payment (provider, provider_payment_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_recruiter_subscription_payment_idempotency ON recruiter_subscription_payment (idempotency_key)');
        $this->addSql('ALTER TABLE recruiter_subscription_payment ADD CONSTRAINT FK_333D85CD979B1AD6 FOREIGN KEY (company_id) REFERENCES company (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE recruiter_subscription_payment ADD CONSTRAINT FK_333D85CDD09FDF9D FOREIGN KEY (initiated_by_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE recruiter_subscription_payment DROP CONSTRAINT FK_333D85CD979B1AD6');
        $this->addSql('ALTER TABLE recruiter_subscription_payment DROP CONSTRAINT FK_333D85CDD09FDF9D');
        $this->addSql('DROP TABLE recruiter_subscription_payment');

        $this->addSql('ALTER TABLE company DROP recruiter_plan_code');
        $this->addSql('ALTER TABLE company DROP recruiter_plan_started_at');
        $this->addSql('ALTER TABLE company DROP recruiter_plan_expires_at');
    }
}

