<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260217233000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add reason code and evidence date to points claims, plus append-only review event table';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('ALTER TABLE points_claim ADD decision_reason_code VARCHAR(80) DEFAULT NULL');
        $this->addSql('ALTER TABLE points_claim ADD evidence_issued_at DATE DEFAULT NULL');

        $this->addSql('CREATE TABLE points_claim_review_event (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, points_claim_id INT NOT NULL, actor_id INT DEFAULT NULL, action VARCHAR(40) NOT NULL, reason_code VARCHAR(80) DEFAULT NULL, reason_text TEXT DEFAULT NULL, metadata JSON DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_B4DA3B066CBCC95D ON points_claim_review_event (points_claim_id)');
        $this->addSql('CREATE INDEX IDX_B4DA3B06010A4ECE ON points_claim_review_event (actor_id)');
        $this->addSql('CREATE INDEX idx_points_claim_review_event_claim ON points_claim_review_event (points_claim_id, created_at)');
        $this->addSql('ALTER TABLE points_claim_review_event ADD CONSTRAINT FK_B4DA3B066CBCC95D FOREIGN KEY (points_claim_id) REFERENCES points_claim (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE points_claim_review_event ADD CONSTRAINT FK_B4DA3B06010A4ECE FOREIGN KEY (actor_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE points_claim_review_event DROP CONSTRAINT FK_B4DA3B066CBCC95D');
        $this->addSql('ALTER TABLE points_claim_review_event DROP CONSTRAINT FK_B4DA3B06010A4ECE');
        $this->addSql('DROP TABLE points_claim_review_event');

        $this->addSql('ALTER TABLE points_claim DROP decision_reason_code');
        $this->addSql('ALTER TABLE points_claim DROP evidence_issued_at');
    }
}
