<?php

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260212130000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Drop moderation review table and cleanup statuses';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('DROP TABLE moderation_review');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('CREATE TABLE moderation_review (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, offer_id INT NOT NULL, reviewer_id INT NOT NULL, decision VARCHAR(20) NOT NULL, reason TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_1D823BE329D6873E ON moderation_review (offer_id)');
        $this->addSql('CREATE INDEX IDX_1D823BE3E99FD0C4 ON moderation_review (reviewer_id)');
        $this->addSql('ALTER TABLE moderation_review ADD CONSTRAINT FK_1D823BE329D6873E FOREIGN KEY (offer_id) REFERENCES offer (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE moderation_review ADD CONSTRAINT FK_1D823BE3E99FD0C4 FOREIGN KEY (reviewer_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }
}
