<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260216173000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add automated impact score and points ledger tables';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE impact_score (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, offer_id INT NOT NULL, society_score INT NOT NULL, biodiversity_score INT NOT NULL, ghg_score INT NOT NULL, total_score INT NOT NULL, confidence DOUBLE PRECISION NOT NULL, rule_version VARCHAR(40) NOT NULL, evidence JSON NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, is_automated BOOLEAN DEFAULT true NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_CBEED03A53C674EE ON impact_score (offer_id)');
        $this->addSql('ALTER TABLE impact_score ADD CONSTRAINT FK_CBEED03A53C674EE FOREIGN KEY (offer_id) REFERENCES offer (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql('CREATE TABLE points_ledger_entry (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, company_id INT DEFAULT NULL, user_id INT DEFAULT NULL, entry_type VARCHAR(20) NOT NULL, points INT NOT NULL, reason VARCHAR(255) NOT NULL, reference_type VARCHAR(40) NOT NULL, reference_id INT DEFAULT NULL, rule_version VARCHAR(40) NOT NULL, idempotency_key VARCHAR(120) NOT NULL, metadata JSON DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_points_ledger_entry_idempotency_key ON points_ledger_entry (idempotency_key)');
        $this->addSql('CREATE INDEX IDX_6DF7A56B979B1AD6 ON points_ledger_entry (company_id)');
        $this->addSql('CREATE INDEX IDX_6DF7A56BA76ED395 ON points_ledger_entry (user_id)');
        $this->addSql('ALTER TABLE points_ledger_entry ADD CONSTRAINT FK_6DF7A56B979B1AD6 FOREIGN KEY (company_id) REFERENCES company (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE points_ledger_entry ADD CONSTRAINT FK_6DF7A56BA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE impact_score DROP CONSTRAINT FK_CBEED03A53C674EE');
        $this->addSql('ALTER TABLE points_ledger_entry DROP CONSTRAINT FK_6DF7A56B979B1AD6');
        $this->addSql('ALTER TABLE points_ledger_entry DROP CONSTRAINT FK_6DF7A56BA76ED395');
        $this->addSql('DROP TABLE impact_score');
        $this->addSql('DROP TABLE points_ledger_entry');
    }
}
