<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260217190000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add points claim table for evidence-based company points attribution';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE points_claim (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, company_id INT NOT NULL, offer_id INT DEFAULT NULL, reviewed_by_id INT DEFAULT NULL, claim_type VARCHAR(40) NOT NULL, status VARCHAR(20) NOT NULL, requested_points INT NOT NULL, approved_points INT DEFAULT NULL, evidence_documents JSON NOT NULL, external_checks JSON DEFAULT NULL, evidence_score INT DEFAULT 0 NOT NULL, decision_reason TEXT DEFAULT NULL, rule_version VARCHAR(40) NOT NULL, idempotency_key VARCHAR(120) NOT NULL, reviewed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_A8CB3A45979B1AD6 ON points_claim (company_id)');
        $this->addSql('CREATE INDEX IDX_A8CB3A45C2EF3C5 ON points_claim (offer_id)');
        $this->addSql('CREATE INDEX IDX_A8CB3A45E539A48A ON points_claim (reviewed_by_id)');
        $this->addSql('CREATE INDEX idx_points_claim_company_status ON points_claim (company_id, status)');
        $this->addSql('CREATE UNIQUE INDEX uniq_points_claim_idempotency_key ON points_claim (idempotency_key)');
        $this->addSql('ALTER TABLE points_claim ADD CONSTRAINT FK_A8CB3A45979B1AD6 FOREIGN KEY (company_id) REFERENCES company (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE points_claim ADD CONSTRAINT FK_A8CB3A45C2EF3C5 FOREIGN KEY (offer_id) REFERENCES offer (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE points_claim ADD CONSTRAINT FK_A8CB3A45E539A48A FOREIGN KEY (reviewed_by_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE points_claim DROP CONSTRAINT FK_A8CB3A45979B1AD6');
        $this->addSql('ALTER TABLE points_claim DROP CONSTRAINT FK_A8CB3A45C2EF3C5');
        $this->addSql('ALTER TABLE points_claim DROP CONSTRAINT FK_A8CB3A45E539A48A');
        $this->addSql('DROP TABLE points_claim');
    }
}
