<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260224103000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add append-only points policy decision audit log';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE points_policy_decision (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, company_id INT DEFAULT NULL, user_id INT DEFAULT NULL, decision_status VARCHAR(10) NOT NULL, reason_code VARCHAR(80) NOT NULL, reason_text TEXT DEFAULT NULL, reference_type VARCHAR(40) NOT NULL, reference_id INT DEFAULT NULL, points INT NOT NULL, rule_version VARCHAR(40) NOT NULL, metadata JSON DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_points_policy_decision_company_created_at ON points_policy_decision (company_id, created_at)');
        $this->addSql('CREATE INDEX idx_points_policy_decision_user_created_at ON points_policy_decision (user_id, created_at)');
        $this->addSql('CREATE INDEX idx_points_policy_decision_reference ON points_policy_decision (reference_type, reference_id, created_at)');
        $this->addSql("ALTER TABLE points_policy_decision ADD CONSTRAINT chk_points_policy_decision_status CHECK (decision_status IN ('ALLOW', 'BLOCK'))");
        $this->addSql('ALTER TABLE points_policy_decision ADD CONSTRAINT FK_32D88C1E979B1AD6 FOREIGN KEY (company_id) REFERENCES company (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE points_policy_decision ADD CONSTRAINT FK_32D88C1EA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE points_policy_decision DROP CONSTRAINT FK_32D88C1E979B1AD6');
        $this->addSql('ALTER TABLE points_policy_decision DROP CONSTRAINT FK_32D88C1EA76ED395');
        $this->addSql('ALTER TABLE points_policy_decision DROP CONSTRAINT chk_points_policy_decision_status');
        $this->addSql('DROP TABLE points_policy_decision');
    }
}
